import { Account } from '../types';

export const INITIAL_ACCOUNTS: Account[] = [
  { kode: '100', nama: 'KAS', kelompok: 'Aset', kategori: 'Aset Lancar' },
  { kode: '110', nama: 'BANK BRI', kelompok: 'Aset', kategori: 'Aset Lancar' },
  { kode: '111', nama: 'BANK MANDIRI', kelompok: 'Aset', kategori: 'Aset Lancar' },
  { kode: '112', nama: 'BANK BNI', kelompok: 'Aset', kategori: 'Aset Lancar' },
  { kode: '113', nama: 'BANK LAINNYA', kelompok: 'Aset', kategori: 'Aset Lancar' },
  { kode: '200', nama: 'PERSEDIAAN SEPEDA', kelompok: 'Aset', kategori: 'Aset Lancar' },
  { kode: '201', nama: 'PERSEDIAAN SPAREPART', kelompok: 'Aset', kategori: 'Aset Lancar' },
  { kode: '202', nama: 'PERSEDIAAN AKSESORIS', kelompok: 'Aset', kategori: 'Aset Lancar' },
  { kode: '203', nama: 'PERSEDIAAN LAINNYA', kelompok: 'Aset', kategori: 'Aset Lancar' },
  { kode: '300', nama: 'PIUTANG USAHA', kelompok: 'Aset', kategori: 'Aset Lancar' },
  { kode: '400', nama: 'PERALATAN KANTOR', kelompok: 'Aset', kategori: 'Aset Tetap' },
  { kode: '401', nama: 'KENDARAAN', kelompok: 'Aset', kategori: 'Aset Tetap' },
  { kode: '402', nama: 'AKUMULASI PENYUSUTAN', kelompok: 'Kontra Aset', kategori: 'Kontra Aset' },
  { kode: '500', nama: 'UTANG USAHA', kelompok: 'Kewajiban', kategori: 'Kewajiban Lancar' },
  { kode: '510', nama: 'UTANG BANK BRI', kelompok: 'Kewajiban', kategori: 'Kewajiban Lancar' },
  { kode: '511', nama: 'UTANG BANK MANDIRI', kelompok: 'Kewajiban', kategori: 'Kewajiban Lancar' },
  { kode: '512', nama: 'UTANG BANK BNI', kelompok: 'Kewajiban', kategori: 'Kewajiban Lancar' },
  { kode: '513', nama: 'UTANG BANK LAINNYA', kelompok: 'Kewajiban', kategori: 'Kewajiban Lancar' },
  { kode: '600', nama: 'MODAL PEMILIK', kelompok: 'Modal', kategori: 'Modal' },
  { kode: '601', nama: 'PRIVE', kelompok: 'Modal', kategori: 'Prive' },
  { kode: '700', nama: 'PENJUALAN SEPEDA', kelompok: 'Pendapatan', kategori: 'Pendapatan' },
  { kode: '701', nama: 'PENJUALAN SPAREPART', kelompok: 'Pendapatan', kategori: 'Pendapatan' },
  { kode: '702', nama: 'PENJUALAN AKSESORIS', kelompok: 'Pendapatan', kategori: 'Pendapatan' },
  { kode: '703', nama: 'PENDAPATAN JASA', kelompok: 'Pendapatan', kategori: 'Pendapatan' },
  { kode: '704', nama: 'DISKON PENJUALAN', kelompok: 'Kontra Pendapatan', kategori: 'Kontra Pendapatan' },
  { kode: '705', nama: 'PENDAPATAN LAINNYA', kelompok: 'Pendapatan', kategori: 'Pendapatan' },
  { kode: '800', nama: 'HPP SEPEDA', kelompok: 'HPP', kategori: 'HPP' },
  { kode: '801', nama: 'HPP SPAREPART', kelompok: 'HPP', kategori: 'HPP' },
  { kode: '802', nama: 'HPP AKSESORIS', kelompok: 'HPP', kategori: 'HPP' },
  { kode: '803', nama: 'HPP LAINNYA', kelompok: 'HPP', kategori: 'HPP' },
  { kode: '900', nama: 'BEBAN GAJI KARYAWAN', kelompok: 'Beban', kategori: 'Beban Operasional' },
  { kode: '901', nama: 'BEBAN TRANSPORT', kelompok: 'Beban', kategori: 'Beban Operasional' },
  { kode: '902', nama: 'BEBAN PDAM', kelompok: 'Beban', kategori: 'Beban Operasional' },
  { kode: '903', nama: 'BEBAN ADM BANK', kelompok: 'Beban', kategori: 'Beban Operasional' },
  { kode: '904', nama: 'BEBAN PERLENGKAPAN TOKO', kelompok: 'Beban', kategori: 'Beban Operasional' },
  { kode: '905', nama: 'BEBAN LISTRIK', kelompok: 'Beban', kategori: 'Beban Operasional' },
  { kode: '906', nama: 'BEBAN PERBAIKAN', kelompok: 'Beban', kategori: 'Beban Operasional' },
  { kode: '907', nama: 'BEBAN INTERNET & TELEPON', kelompok: 'Beban', kategori: 'Beban Operasional' },
  { kode: '908', nama: 'BEBAN PENYUSUTAN', kelompok: 'Beban', kategori: 'Beban Operasional' },
  { kode: '910', nama: 'BEBAN BUNGA BANK', kelompok: 'Beban', kategori: 'Beban Keuangan' },
  { kode: '911', nama: 'BEBAN DENDA BANK', kelompok: 'Beban', kategori: 'Beban Keuangan' },
  { kode: '909', nama: 'BEBAN LAINNYA', kelompok: 'Beban', kategori: 'Beban Operasional' }
];

export const INITIAL_PRODUCTS = [
  { kode: 'HB-SPD-001', nama: 'Sepeda Gunung MTB 26 Inc', kategori: 'Sepeda', satuan: 'unit', modal: 1200000, jual: 1650000, stok: 5 },
  { kode: 'HB-SPD-002', nama: 'Sepeda Lipat 20 Inc Alloy', kategori: 'Sepeda', satuan: 'unit', modal: 1500000, jual: 2100000, stok: 3 },
  { kode: 'HB-SPT-001', nama: 'Rantai Sepeda 8-Speed', kategori: 'Sparepart', satuan: 'pcs', modal: 45000, jual: 75000, stok: 15 },
  { kode: 'HB-SPT-002', nama: 'Ban Dalam 26x1.95 Swallow', kategori: 'Sparepart', satuan: 'pcs', modal: 25000, jual: 40000, stok: 20 },
  { kode: 'HB-AKS-001', nama: 'Helm Sepeda Roadbike Aero', kategori: 'Aksesoris', satuan: 'pcs', modal: 85000, jual: 135000, stok: 10 },
  { kode: 'HB-AKS-002', nama: 'Lampu Depan Charge USB', kategori: 'Aksesoris', satuan: 'pcs', modal: 35000, jual: 60000, stok: 12 }
];
